# Generated by Django 5.2.8 on 2025-12-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books & Supplies'), ('jewelry', 'Jewelry & Accessories'), ('keys', 'Keys & ID Cards'), ('bags', 'Bags & Backpacks'), ('water', 'Water Bottles'), ('glasses', 'Eyeglasses'), ('other', 'Other')], max_length=50),
        ),
    ]
