# Generated by Django 5.2.8 on 2025-12-05 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='returned_to',
            field=models.ForeignKey(blank=True, help_text='User who received the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
