# Generated by Django 5.2.8 on 2025-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_returned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('bags', 'Bags & Cases'), ('supplies', 'School Supplies'), ('keys', 'Keys & ID Cards'), ('accessories', 'Jewelry & Accessories'), ('equipment', 'Sports & Activity Equipment'), ('personal', 'Personal Items'), ('other', 'Other')], max_length=50),
        ),
    ]
