# Generated by Django 5.2.8 on 2025-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('rejected', 'Rejected Claim'), ('verified', 'Verified'), ('returned', 'Returned'), ('discarded', 'Discarded / Donated')], default='unclaimed', max_length=20),
        ),
    ]
