# Generated by Django 5.2.8 on 2025-12-05 21:41

from django.db import migrations


def update_status_values(apps, schema_editor):
    """Update old status values to new ones"""
    Item = apps.get_model('items', 'Item')
    # Update 'available' to 'unclaimed' for all items
    Item.objects.filter(status='available').update(status='unclaimed')


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_status'),
    ]

    operations = [
        migrations.RunPython(update_status_values, reverse_code=migrations.RunPython.noop),
    ]
