# Generated by Django 5.2.8 on 2025-12-05 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_update_status_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discard_date',
            field=models.DateTimeField(blank=True, help_text='Date when item was discarded/donated', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discard_notes',
            field=models.TextField(blank=True, help_text='Additional notes about disposal/donation'),
        ),
        migrations.AddField(
            model_name='item',
            name='discard_reason',
            field=models.CharField(blank=True, help_text="Reason for discarding (e.g., 'Unclaimed for 90 days', 'Damaged', etc.)", max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='discarded_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who discarded the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
