# Generated by Django 5.2.8 on 2026-01-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='verified_date',
            field=models.DateTimeField(blank=True, help_text='Date when claim was verified (starts 60-day countdown)', null=True),
        ),
    ]
